### ISSUE TITLE
No such directory

### ISSUE THREAD

**Issue by brentleeper** [esteban-mallen/homebridge-roomba-stv#10]
pi@raspberrypi:~ $ sudo npm run getrobotpwd 192.168.1.230
npm ERR! Error: ENOENT: no such file or directory, open '/home/pi/node_modules/getrobotpwd/package.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "getrobotpwd" "192.168.1.230"
npm ERR! cwd /home/pi
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/node_modules/getrobotpwd/package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by esteban-mallen** [comment]
Make sure to run it from where you installed the plugin (run `npm root -g` to find it)

**Comment by brentleeper** [comment]
Thanks for your response. I got it working. There was an issue with nodejs
