### ISSUE TITLE
Roomba not responding to Plugin - Freezing Homebridge

### ISSUE THREAD

**Issue by solbadguy2010** [esteban-mallen/homebridge-roomba-stv#35]
My Roomba is online, working fine, is controllable by its App and IFTTT. I used it with your Plugin before, but now its showing "refreshing" and "No Answer" in Homekit. Additionally all other Homekit accessories are also in the same state as long as your Plugin is installed and so basically lock the homebridge. 

To my surprise the log looks fine. It also shows "starting Roomba" when i use the button in "homebridge-config-ui-x" but nothing happens. I attach a picture:

<img width="1369" alt="Bildschirmfoto 2019-07-17 um 08 48 08" src="https://user-images.githubusercontent.com/30244171/61353696-b5b74080-a870-11e9-9aad-7cd47b07aa1c.png">

Are you able to fix this issue?

**Comment by malmentm** [comment]
I got about the same issue, as soon the roomba is offline thius plugin freezes up the homebridge and cause all other plugins to med non responsive

**Comment by solbadguy2010** [comment]
I think mr. Mallen is not updating this Plugin anymore. Maybe someone is forking this some day?

**Comment by shogun88888888** [comment]
Same Issue

**Comment by RaymondMouthaan** [comment]
Have you guys updated to the latest version (1.5.0) ? Seems to me that mr. Mallen has update the plugin two days ago.

**Comment by solbadguy2010** [comment]
Just testet. Plug-In is working again. Than you Mr. Mallen!

**Comment by djrams10** [comment]
I find myself with the same problem again. Nobody else?

**Comment by solbadguy2010** [comment]
Not exactly „again“. It was never solved for me. Currently i switched to IFTTT. Its not as detailed as this plugin, but does the job without killing homebridge.

**Comment by djrams10** [comment]
Thank you for your return, it's a shame not to be able to have the return of state of the roomba.

**Comment by solbadguy2010** [comment]
Yes. I would also love to use this Plugin again. It works well as long as the Roomba doesn‘t get Stuck. But as soon as the roomba is stuck and out of battery the plugin freezes from the point it can‘t reach the roomba.

**Comment by djrams10** [comment]
ok.  thanks for the information.  it hangs very rarely.

**Comment by RaymondMouthaan** [comment]
Guys, its kinda weird you having these issues. I am running this plugin for several months now and not even once my HomeBridge freezes ...

**Comment by solbadguy2010** [comment]
As said, it only hangs when the Roomba get stuck, battery depletes and he is going offline.

**Comment by djrams10** [comment]
actually, it's stuck only today and homebridge has blocked

**Comment by djrams10** [comment]
Hello, I would like to reopen the topic as I am currently having the same problem.  I am the only one ?  Thank you
