### ISSUE TITLE
i7+ with Clean Base

### ISSUE THREAD

**Issue by DaveyGiesen** [esteban-mallen/homebridge-roomba-stv#61]
I tried this plugin but when enabling the Roomba i7+ with Clean Base it will start the cleaning base and not start cleaning the rooms. Someone experiencing the same problem? 

I got the latest version of this plugin and homebridge (1.1.0).

**Comment by dfct** [comment]
For what it may be worth to others stumbling across this: it works fine for me, i7+ with Clean Base.

**Comment by i3laze** [comment]
Indeed it does.

By the way, does anyone sometimes experience 5-30 sec delays with i7 before it actually starts cleaning or returning home? Got delays each 3 commands out of 10 even when using its hardware buttons.
Began for my i7+ on f/w 3.8.3.

Issue is not related to this plugin or HomeBridge.

**Comment by DaveyGiesen** [comment]
Works now fine, I don't know what the solution is :)
