### ISSUE TITLE
Does this work with the s9?

### ISSUE THREAD

**Issue by whreams** [esteban-mallen/homebridge-roomba-stv#64]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **Plugin**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by Pblondin123** [comment]
same question!  about to test soon.

**Comment by Pblondin123** [comment]
seems to work for the s9.   Had trouble to figure out how to use the getrobotpwd command, i.e. absolutely needs to run from the plugin folder.

**Comment by whreams** [comment]
I agree it works with the S9.  Requesting to close.
