### ISSUE TITLE
Roomba not responding to Plugin - Freezing Homebridge

### ISSUE THREAD

**Issue by djrams10** [esteban-mallen/homebridge-roomba-stv#73]
Hello, it's been a week since I noticed that the rumba accessory is unresponsive, resulting in a homebridge freeze.  everything is fine after rebooting homebridge but about 24 hours after the problem comes back.  someone can help me ?  Thank you

**Comment by Pblondin123** [comment]
probably same issue as issue 66: configure without autoRefreshEnabled nor keepAliveEnabled, basically an on off switch.   I have been using mine that way for months and although not much features, HB is stable.

**Comment by djrams10** [comment]
It's ok. Thanks 👍🏼
