### ISSUE TITLE
Interval feature does not improve response time

### ISSUE THREAD

**Issue by nitaybz** [esteban-mallen/homebridge-roomba-stv#9]
I think there is an issue with the code... as I understand, you fetch the status every X seconds and save it to a file for 30 seconds. so if the number of seconds between each poll is bigger than 30 seconds it will still need to poll the device.
I, for example, set it to poll every 180 seconds

I would suggest keeping the file for the same duration as the interval or even a few seconds more.

also, it's important for the status to change in the file with every SET command.

Those are only my suggestion, you're doing a great job and i love using your plugin,
Thanks!

**Comment by esteban-mallen** [comment]
Will check! Thanks for the feedback!

**Comment by esteban-mallen** [comment]
@nitaybz don't think I forgot about this, I just got sidetracked to other things
